"use client";

import { useEffect, useState } from "react";
import { ImSpinner as SpinnerIcon } from "react-icons/im";
import { HiDocumentDuplicate as DuplicateIcon } from "react-icons/hi2";
import ReactMarkdown from "react-markdown";

import { type RetrospectiveData } from "@/types/Retro";
import { endRetrospective, generateAIContent } from "@/app/actions";
import { useUserSession } from "@/hooks/user-session-context";
import { EndRetroDialog } from "./EndRetroDialog";
import { socket } from "@/socket";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

interface EndRetroContainerProps {
  retrospectiveData: RetrospectiveData;
}

export function EndRetroContainer({
  retrospectiveData,
}: EndRetroContainerProps) {
  const { userSession } = useUserSession();
  const { toast } = useToast();
  const [finalRetroSummary, setFinalRetroSummary] = useState<string>("");
  const [isLoadingFinalContent, setIsLoadingFinalContent] =
    useState<boolean>(false);

  const hasRetroEnded = retrospectiveData.status === "ended";
  const isCurrentUserAdmin = retrospectiveData.adminId === userSession?.id;

  useEffect(() => {
    socket.on("retro-ended-user", (content: string) => {
      setFinalRetroSummary(content);
    });

    return () => {
      socket.off("retro-ended-user");
    };
  }, []);

  const handleEndRetro = async () => {
    setIsLoadingFinalContent(true);
    const retrospective = await endRetrospective(retrospectiveData.id);

    if (retrospective) {
      const generatedAIContent = await generateAIContent(retrospective);

      if (!generatedAIContent) {
        setFinalRetroSummary("An Error has ocurred. No summary generated");
        setIsLoadingFinalContent(false);
        return;
      }

      setFinalRetroSummary(generatedAIContent);

      socket.emit("retro-ended", retrospective.id, generatedAIContent);
    }

    setIsLoadingFinalContent(false);
  };

  if (isLoadingFinalContent) {
    return (
      <SpinnerIcon size={50} className="animate-spin text-violet-700 mt-12" />
    );
  }

  const handleCopyToClipboard = () => {
    try {
      navigator.clipboard.writeText(finalRetroSummary);
      toast({
        title: "Retrospective data copied to the clipboard",
      });
    } catch (error) {
      toast({
        title: "Error copying to the clipboard",
      });
    }
  };

  return (
    <div className="mt-6 relative w-full">
      {!hasRetroEnded ? (
        <EndRetroDialog
          onEndRetro={handleEndRetro}
          isCurrentUserAdmin={isCurrentUserAdmin}
        />
      ) : (
        <div className="w-full p-4">
          <h1 className="text-5xl font-bold ">Congratulations!</h1>
          <h2 className="text-xl font-medium text-neutral-500 mt-1">
            This Retrospective meeting is finish
          </h2>
          <p className="my-4">
            Here you can find a summary generated by AI:{" "}
            <span className="text-xs text-violet-800">
              powered by Gemini AI
            </span>
          </p>
          <div className="hover:bg-neutral-100 p-4 group rounded-lg border border-transparent hover:border-neutral-200 relative mb-4">
            <ReactMarkdown className="markdown">
              {finalRetroSummary}
            </ReactMarkdown>
            <Button
              variant="outline"
              size="icon"
              className="invisible group-hover:visible absolute top-4 right-4 text-neutral-500"
              onClick={handleCopyToClipboard}
            >
              <DuplicateIcon size={16} />
            </Button>
          </div>
          <span className="italic text-sm">
            Disclaimer: The data is fully private and its not share with any
            external sources
          </span>
        </div>
      )}
    </div>
  );
}
